version: '2'
services:
  web:
    image: snelg/cake3byudev
    ports:
     - "80:80"
     - "443:443"
    volumes:
     - .:/cake
    depends_on:
     - mysql
  mysql:
    image: mysql/mysql-server
    environment:
     - MYSQL_ROOT_PASSWORD=__DEVPASSWORD__
    volumes:
     - devdata:/var/lib/mysql
     - ./dev-init-data:/docker-entrypoint-initdb.d
  setup:
    image: composer/composer
    command: install --ignore-platform-reqs
    volumes:
     - .:/app
volumes:
  devdata:
